port: 7890
socks-port: 7891
redir-port: 12345
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
      - 114.114.114.114
      - 223.5.5.5
      - 1.1.1.1
      - 1.0.0.1
      - tls://dns.rubyfish.cn:853
  fallback:
      - tls://1.1.1.1:853
      - tls://1.0.0.1:853
      - tls://dns.google:853

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 国家选择
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 自动选择
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    proxies:
  - name: 手动选择
    type: select
    proxies:
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - REJECT
      - DIRECT
  - name: 社交服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 全球媒体
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: Emby视频
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 国家选择
    type: select
    proxies:
      - 美国节点
      - 狮城节点
      - 香港节点
      - 其他国家
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 失败切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:

rule-providers: # rule-providers from Logyalsoldier/clash-rules and LM-Firefly/Rules
  Apple:
    type: http
    behavior: domain # https://github.com/Dreamacro/clash/issues/1165
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./TopFreeProxies/ruleset/apple.yaml
  iCloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./TopFreeProxies/ruleset/icloud.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/Microsoft.yaml"
    path: ./TopFreeProxies/ruleset/microsoft.yaml
    interval: 86400
  Google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./TopFreeProxies/ruleset/google.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/GlobalMedia.yaml"
    path: ./TopFreeProxies/ruleset/globalmedia.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./TopFreeProxies/ruleset/telegramcidr.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Twitter.yaml"
    path: ./TopFreeProxies/ruleset/twitter.yaml
    interval: 86400
  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./TopFreeProxies/ruleset/private.yaml
    interval: 86400
  LAN-CIDR:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./TopFreeProxies/ruleset/lancidr.yaml
    interval: 86400
  Local-LAN:
    type: http
    behavior: classical
    url: "https://raw.fastgit.org/LM-Firefly/Rules/master/Clash-RuleSet-Classical/Special/Local-LAN.yaml"
    path: ./TopFreeProxies/ruleset/local-lan.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./TopFreeProxies/ruleset/proxy.yaml
    interval: 86400
  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./TopFreeProxies/ruleset/reject.yaml
    interval: 86400

rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

  - GEOIP,CN,DIRECT # GeoIP2 数据库 from Hackl0us/GeoIP2-CN

  - IP-CIDR,10.240.0.0/24,DIRECT,no-resolve
  - RULE-SET,LAN-CIDR,DIRECT,no-resolve
  - RULE-SET,Reject,REJECT,no-resolve
  - RULE-SET,Private,DIRECT,no-resolve
  - RULE-SET,Local-LAN,DIRECT,no-resolve

  - DOMAIN-SUFFIX,emby.wtf,Emby视频,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - RULE-SET,Apple,苹果服务
  - RULE-SET,iCloud,苹果服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Twitter,社交服务
  - RULE-SET,Telegram,社交服务
  - RULE-SET,GlobalMedia,全球媒体

  - RULE-SET,Proxy,节点选择
  - MATCH,漏网之鱼
